import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { NavigationProvider } from "@/components/navigation";

const heading = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-heading",
});

const notoSans = Noto_Sans_JP({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "マルバツクイズメーカー",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        notoSans.variable,
        heading.variable,
      )}
    >
      <body className="min-h-full bg-yellow-800">
        <NavigationProvider>
          <div className=" mx-auto min-h-screen max-w-lg w-full bg-[repeating-linear-gradient(-45deg,#efb100,#efb100_15px,#fcc800_15px,#fcc800_30px)]">
            {children}
          </div>
        </NavigationProvider>
      </body>
    </html>
  );
}
